# Generated by Django 3.2 on 2023-02-21 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="title",
            name="rating",
            field=models.IntegerField(default=None, null=True),
        ),
    ]
